/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package reversi.gameengine;

public class Board {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Board(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Board obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        reversi_game_engineJNI.delete_Board(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setState(SWIGTYPE_p_p_Piece value) {
    reversi_game_engineJNI.Board_state_set(swigCPtr, this, SWIGTYPE_p_p_Piece.getCPtr(value));
  }

  public SWIGTYPE_p_p_Piece getState() {
    long cPtr = reversi_game_engineJNI.Board_state_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_Piece(cPtr, false);
  }

  public void setDifficulty(Difficulty value) {
    reversi_game_engineJNI.Board_difficulty_set(swigCPtr, this, value.swigValue());
  }

  public Difficulty getDifficulty() {
    return Difficulty.swigToEnum(reversi_game_engineJNI.Board_difficulty_get(swigCPtr, this));
  }

  public void setHistoryBack(Movement value) {
    reversi_game_engineJNI.Board_historyBack_set(swigCPtr, this, Movement.getCPtr(value), value);
  }

  public Movement getHistoryBack() {
    long cPtr = reversi_game_engineJNI.Board_historyBack_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Movement(cPtr, false);
  }

  public void setHistoryForward(Movement value) {
    reversi_game_engineJNI.Board_historyForward_set(swigCPtr, this, Movement.getCPtr(value), value);
  }

  public Movement getHistoryForward() {
    long cPtr = reversi_game_engineJNI.Board_historyForward_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Movement(cPtr, false);
  }

  public void setNoOfMovesBack(int value) {
    reversi_game_engineJNI.Board_noOfMovesBack_set(swigCPtr, this, value);
  }

  public int getNoOfMovesBack() {
    return reversi_game_engineJNI.Board_noOfMovesBack_get(swigCPtr, this);
  }

  public void setLastPiecetypeMoved(PlayerType value) {
    reversi_game_engineJNI.Board_lastPiecetypeMoved_set(swigCPtr, this, value.swigValue());
  }

  public PlayerType getLastPiecetypeMoved() {
    return PlayerType.swigToEnum(reversi_game_engineJNI.Board_lastPiecetypeMoved_get(swigCPtr, this));
  }

  public void setNoOfMovesFoward(int value) {
    reversi_game_engineJNI.Board_noOfMovesFoward_set(swigCPtr, this, value);
  }

  public int getNoOfMovesFoward() {
    return reversi_game_engineJNI.Board_noOfMovesFoward_get(swigCPtr, this);
  }

  public void setInitialized(boolean value) {
    reversi_game_engineJNI.Board_initialized_set(swigCPtr, this, value);
  }

  public boolean getInitialized() {
    return reversi_game_engineJNI.Board_initialized_get(swigCPtr, this);
  }

  public void setSize(int value) {
    reversi_game_engineJNI.Board_size_set(swigCPtr, this, value);
  }

  public int getSize() {
    return reversi_game_engineJNI.Board_size_get(swigCPtr, this);
  }

  public void setCustom(boolean value) {
    reversi_game_engineJNI.Board_custom_set(swigCPtr, this, value);
  }

  public boolean getCustom() {
    return reversi_game_engineJNI.Board_custom_get(swigCPtr, this);
  }

  public void setInitialState(SWIGTYPE_p_p_Piece value) {
    reversi_game_engineJNI.Board_initialState_set(swigCPtr, this, SWIGTYPE_p_p_Piece.getCPtr(value));
  }

  public SWIGTYPE_p_p_Piece getInitialState() {
    long cPtr = reversi_game_engineJNI.Board_initialState_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_Piece(cPtr, false);
  }

  public void setPlayer1(Player value) {
    reversi_game_engineJNI.Board_player1_set(swigCPtr, this, Player.getCPtr(value), value);
  }

  public Player getPlayer1() {
    long cPtr = reversi_game_engineJNI.Board_player1_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Player(cPtr, false);
  }

  public void setPlayer2(Player value) {
    reversi_game_engineJNI.Board_player2_set(swigCPtr, this, Player.getCPtr(value), value);
  }

  public Player getPlayer2() {
    long cPtr = reversi_game_engineJNI.Board_player2_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Player(cPtr, false);
  }

  public Board() {
    this(reversi_game_engineJNI.new_Board(), true);
  }

}
