/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package reversi.gameengine;

public enum Difficulty {
  EASY,
  INTERMEDIATE,
  HARD;

  public final int swigValue() {
    return swigValue;
  }

  public static Difficulty swigToEnum(int swigValue) {
    Difficulty[] swigValues = Difficulty.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (Difficulty swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + Difficulty.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private Difficulty() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private Difficulty(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private Difficulty(Difficulty swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

