/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package reversi.gameengine;

public class Movement {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Movement(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Movement obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        reversi_game_engineJNI.delete_Movement(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPieceType(PlayerType value) {
    reversi_game_engineJNI.Movement_pieceType_set(swigCPtr, this, value.swigValue());
  }

  public PlayerType getPieceType() {
    return PlayerType.swigToEnum(reversi_game_engineJNI.Movement_pieceType_get(swigCPtr, this));
  }

  public void setX(int value) {
    reversi_game_engineJNI.Movement_x_set(swigCPtr, this, value);
  }

  public int getX() {
    return reversi_game_engineJNI.Movement_x_get(swigCPtr, this);
  }

  public void setY(int value) {
    reversi_game_engineJNI.Movement_y_set(swigCPtr, this, value);
  }

  public int getY() {
    return reversi_game_engineJNI.Movement_y_get(swigCPtr, this);
  }

  public Movement() {
    this(reversi_game_engineJNI.new_Movement(), true);
  }

}
