/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package reversi.gameengine;

public class Piece {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Piece(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Piece obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        reversi_game_engineJNI.delete_Piece(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPieceType(StateFlags value) {
    reversi_game_engineJNI.Piece_pieceType_set(swigCPtr, this, value.swigValue());
  }

  public StateFlags getPieceType() {
    return StateFlags.swigToEnum(reversi_game_engineJNI.Piece_pieceType_get(swigCPtr, this));
  }

  public Piece() {
    this(reversi_game_engineJNI.new_Piece(), true);
  }

}
