/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package reversi.gameengine;

public class Player {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Player(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Player obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        reversi_game_engineJNI.delete_Player(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setIsHuman(boolean value) {
    reversi_game_engineJNI.Player_isHuman_set(swigCPtr, this, value);
  }

  public boolean getIsHuman() {
    return reversi_game_engineJNI.Player_isHuman_get(swigCPtr, this);
  }

  public Player() {
    this(reversi_game_engineJNI.new_Player(), true);
  }

}
