/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package reversi.gameengine;

public enum StateFlags {
  VOID,
  BLACK_PIECE(1),
  WHITE_PIECE(2),
  HELPER;

  public final int swigValue() {
    return swigValue;
  }

  public static StateFlags swigToEnum(int swigValue) {
    StateFlags[] swigValues = StateFlags.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (StateFlags swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + StateFlags.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private StateFlags() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private StateFlags(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private StateFlags(StateFlags swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

